---
- name: Install Packages
  hosts: rpi
  become: true

  tasks:
    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - python3-awsiotsdk ??
        state: present


pip packages
rpi-ws281x
RPi.GPIO
boto3
awsiotsdk
awscrt
awsiot

.bashrc
export PYTHONPATH="$PYTHONPATH:/home/pir/myenv/lib/python3.11/site-packages"
export LAMP_NAME="Lamp-TW"
export LAMP_TOPIC="pi/lamp"
export LAMP_COLOR_NAME="blue"
export LAMP_COLOR_RGB="0,0,255"
export LAMP_ID="Lamp-TW"
export LAMP_ENDPOINT=

alias pilamp="sudo -E ~/myenv/bin/python3 ~/Git/aws_lamp/app/lamp/pi-lamp.py --endpoint $LAMP_ENDPOINT --ca_file ~/Certs/AmazonRootCA1.pem --cert ~/Certs>

